aiidateam/aiida-pseudo

.github/workflows/ci.yml
aiida_pseudo/cli/install.py
aiida_pseudo/cli/params/types.py
aiida_pseudo/cli/utils.py
aiida_pseudo/data/pseudo/pseudo.py
aiida_pseudo/groups/family/pseudo.py
aiida_pseudo/groups/family/sssp.py
setup.json
tests/cli/test_install.py
tests/cli/test_utils.py
tests/conftest.py

This allows to also start using f-strings. All old-style formatted
strings are replaced with the new f-strings introduced in Python 3.6.

Drop support for Python 3.5

---

.style.yapf
aiida_pseudo/groups/family/pseudo.py
tests/groups/family/test_pseudo.py

Fixes #6 
Also create a separate keyword for `structure` instead of overloading
`elements`, which is clearer from a user's perspective.

`PseudoPotentialFamily.get_pseudos`: turn arguments into keyword only

---

aiida_pseudo/data/pseudo/pseudo.py
tests/data/pseudo/test_pseudo.py

Fixes #9 
The `Node.store` method requires keyword arguments to be passable but
the `PseudoPotentialData.store` signature didn't allow any. This could
cause a crash when the data type was used unstored as an input to a
process.

`PseudoPotentialData`: maintain correct signature for `store` method

---

aiida_pseudo/groups/family/pseudo.py
tests/conftest.py
tests/groups/family/test_pseudo.py

Fixes #91
The method was incorrectly returning a mapping of the pseudos onto the
symbols of the structure's kind, thereby discarding the kind name, which
can often be different from the symbol. For example, `aiida-quantumespresso`
uses kind names that suffix the element symbol with a digit in order to
specify different magnetic kinds.

`PseudoPotentialFamily.get_pseudos`: maintain structure kind names

---

aiida_pseudo/data/pseudo/upf.py
tests/data/pseudo/test_upf.py
tests/fixtures/pseudos/upf/Ar.upf
tests/fixtures/pseudos/upf/He.upf
tests/fixtures/pseudos/upf/Kr.upf
tests/fixtures/pseudos/upf/Ne.upf
tests/fixtures/pseudos/upf/Rn.upf

Fixes #23 
This value is required for, among other things, to determine starting
magnetization in spin polarized calculation. Instead of having to parse
the file each time for this value, it is done upon construction of the
node and stored as an attribute.

`UpfData`: automatically parse the Z valence from the file

---

aiida_pseudo/groups/family/pseudo.py
pyproject.toml
tests/groups/family/test_pseudo.py

Fixes #27 
These methods need to be overridden, such that after they have called
the implementation of the `Group` base class, the internal `_pseudos`
class attribute can be updated accordingly. For `clear` this is easy as
it is simply set to `None`, but for `remove_nodes` special care needs to
be taken. It needs to account for the fact that a single node or an
iterable of nodes can be passed as an argument, and that the base class
implementation will not raise if any of the nodes is not actually
contained in the group. So instead of doing the straight forward thing
of removing the nodes from `_pseudos` based on the elements, we remove
them based on the pk, which guarantees we are removing the correct nodes.

`PseudoPotentialFamily`: override `remove_nodes` and `clear`

---

aiida_pseudo/data/pseudo/pseudo.py
tests/data/pseudo/test_common.py

Fixes #28 
The method will return the entry point name under which the subclass of
`PseudoPotentialData` is registered. Note that the entry point name does
not include the entry point group. For example, the `UpfData` plugin is
registered under `aiida.data:pseudo.upf`, but the classmethod will
return the string `pseudo.upf`.

`PseudoPotentialData`: add the `get_entry_point_name` classmethod

---

aiida_pseudo/data/pseudo/pseudo.py
aiida_pseudo/groups/family/pseudo.py
tests/data/pseudo/test_pseudo.py

Fixes #32 
The classmethod has the exact same signature as the constructor but
instead of constructing a new instance straightaway, it will first check
if the database already contains a node with the exact same class (so no
subclassing is used in the query) and with an md5 checksum that matches
that of the bytes of the stream.
If an existing node is matched, that is returned, otherwise a new
instance is constructed and returned unstored.

`PseudoPotentialData`: add the `get_or_create` classmethod 

---

aiida_pseudo/data/pseudo/__init__.py
aiida_pseudo/data/pseudo/jthxml.py
setup.json
tests/data/pseudo/test_jthxml.py
tests/fixtures/pseudos/jthxml/Ar.jthxml
tests/fixtures/pseudos/jthxml/He.jthxml
tests/fixtures/pseudos/jthxml/Ne.jthxml

Fixes #36 
This XML based format is used by Pseudo Dojo for PAW based potentials.

Add the `JthxmlData` data plugin

---

aiida_pseudo/cli/install.py
aiida_pseudo/groups/family/pseudo_dojo.py

The PseudoDojo team recommended to remove support for v0.3 because it is based on a bugged pseudopotential code, so I have removed it.
They have also fixed the remaining inconsistencies (F pseudopotential) in the v0.4 families. So, these families have been added to the valid configurations.

Remove support for PseudoDojo v0.3; enable fixed v0.4 families

---

aiida_pseudo/cli/install.py
aiida_pseudo/groups/family/pseudo_dojo.py

Discussed in issue #40 
Alternative to PR #41 
The range of recommended cutoffs in the PseudoDojo PAW families is relatively small (min 10, 10, 10; max 20, 20, 25 for low, normal, high stringency). So, it seems fairly reasonable to replace placeholder cutoff values (i.e. -1) with the maximum for the corresponding stringency. This is an alternative solution to dropping the pseudos entirely, as proposed in #41

Add support for PseudoDojo PAW pseudos (alternative)

---

aiida_pseudo/groups/family/pseudo_dojo.py

Fixes #46 
Some of the djrepo archives from the Pseudo Dojo contain extraneous
files with incorrect extensions (e.g. a second file for Ge with
extension `.djrepo_old`). This currently means that installing from this
archive raises a `ValueError` since duplicate elements will be found.
Here we add a check that makes sure the extension of the archive
filename is in a list of supported extensions, currently limited to
`.djrepo`. If the extension is incorrect, a warning is raised and the
file is skipped.

`PseudoDojoFamily`: skip repo files with unsupported extension

---

aiida_pseudo/cli/params/options.py
aiida_pseudo/cli/show.py
aiida_pseudo/groups/family/__init__.py
aiida_pseudo/groups/family/cutoffs.py
pyproject.toml
setup.json
tests/cli/test_show.py
tests/conftest.py
tests/groups/mixins/test_cutoffs.py

Fixes #51 
Previously, `aiida-pseudo family show` merely shows the element,
filename and md5 of each pseudo contained within a family. Since the
addition of the `RecommendedCutoffMixin`, families can also specify
recommended cutoffs. Here we add these to the output of the command if
the specified family is a subclass of `RecommendedCutoffMixin`.
In order to test this, a generic pseudo potential family class with the
`RecommendedCutoffMixin` is needed. This was already implemented for the
tests of the mixin itself, which created a new group class on the fly
using the `aiida.orm.groups.GroupMeta` meta class to automatically set
the required type strings. This worked for these tests since they didn't
have to be queried for, however, for the `aiida-pseudo family show`
tests, the CLI command …

CLI: add recommended cutoffs to `aiida-pseudo family show`

---

aiida_pseudo/cli/__init__.py
aiida_pseudo/cli/family.py
aiida_pseudo/cli/params/arguments.py
aiida_pseudo/cli/params/options.py
aiida_pseudo/cli/show.py
tests/cli/test_family.py

Fixes #50 
This command allows to set recommended cutoffs for a given family. The
cutoffs are specified in a JSON file that is given as an argument and
the stringency is specified through the `-s/--stringency` option. If the
stringency already exists, it is simply overwritten.

CLI: add the `aiida-pseudo family cutoffs set` command

---

aiida_pseudo/cli/install.py
aiida_pseudo/common/units.py
aiida_pseudo/groups/family/pseudo_dojo.py
aiida_pseudo/groups/mixins/cutoffs.py
setup.json
tests/conftest.py
tests/groups/mixins/test_cutoffs.py

Fixes #47 
By storing the unit of the cutoffs values explicitly in the extras, it
not only will give more certainty to the user of what the cutoffs mean
because they can inspect the unit, but the `get_recommended_cutoffs`
method can also provide the `unit` argument to automatically convert it
to another unit of energy if so desired.
The conversion between units is provided by the `pint` library, which is
added as a dependency. Users can specify units in the API through
strings using the names that are recognized by `pint`. Both the
shorthand, e.g. `eV`, as well as the long version `electron_volt` can be
used. Other common energy units are `Ry` and `Eh`, for Rydberg and
Hartree atomic units respectively.
The default unit that is set when defining recommended cutoffs is still
set to be …

`RecommendedCutoffMixin`: store the unit of cutoffs in extras

---

aiida_pseudo/cli/family.py
aiida_pseudo/cli/params/options.py
tests/cli/test_family.py

Fixes #64 
Currently the user is not able to specify the units of the plane-wave
energy cutoffs when using the `aiida-pseudo family cutoffs set` command.
This means that the user is limited to only specifying the units in
electronvolt.
Here we add the `-u/--unit` option to the `aiida-pseudo family cutoffs set`
command to allow to user to specify the units of the cutoff values
provided in the CUTOFFS JSON file.

CLI: Add `units` option to `aiida-pseudo family cutoffs set`

---

aiida_pseudo/cli/family.py
tests/cli/test_family.py

Fixes #66 
The command's interface only allows to specify a single stringency at a
time, however, it would use the `set_cutoffs` method internally, which
would override any existing stringencies. This bug is addressed by first
retrieving existing stringencies before adding the new one to it and
setting the ensemble as the new stringencies.
There is an additional limitation that needs to be taken into account,
however. Since the current design only allows for a single energy unit
to be used at a time for all stringencies, when adding a new stringency,
the same unit has to be used. If, in the future, `set_cutoffs` starts to
support setting individual stringencies additively and the family
supports multiple units for the different stringencies, then all of this
logic can be simplified …

CLI: do not override existing stringencies in `family cutoffs set`

---

aiida_pseudo/cli/install.py
aiida_pseudo/cli/utils.py
aiida_pseudo/groups/family/pseudo_dojo.py
aiida_pseudo/groups/family/sssp.py
tests/cli/test_install.py
tests/conftest.py

This serves two purposes: it makes it easier to reuse the download code
outside of the CLI and secondly, it enables the mocking of this part of
the code, which is a heavy operation. Without this, unit testing of this
command would be prohibitively expensive as it would need to download
all files for every test.

CLI: refactor download code from automated install commands

---

aiida_pseudo/cli/install.py
aiida_pseudo/cli/params/options.py
aiida_pseudo/cli/utils.py
aiida_pseudo/groups/family/pseudo_dojo.py
tests/cli/test_install.py
tests/conftest.py

Fixes #63 
The `aiida-pseudo install sssp` and `aiida-pseudo install pseudo-dojo`
automatically download the required files for installing the
corresponding pseudopotential families. Since the entire operation can
sometimes fail, `aiida-pseudo install family` was added in order to
facilitate the manual installation without the automatic download.
Conversely, it may be useful to have the command only download the files
of a particular family, without actually installing them.
The `--download-only` option is added to both automatic family install
commands which will simply write the files to the current working
directory after having downloaded them.

CLI: add `--download-only` option to automatic family install commands

---

aiida_pseudo/cli/family.py
aiida_pseudo/cli/install.py
aiida_pseudo/groups/mixins/cutoffs.py
tests/cli/test_family.py
tests/conftest.py
tests/groups/mixins/test_cutoffs.py

Fixes #68 
Currently the behaviour of the `set_cutoffs` and `get_cutoffs` methods of the
`RecommendedCutoffMixin` class is different. The first sets the cutoffs for all
stringencies along with a default stringency, the second only retrieves the
cutoffs for a specified stringency. This can be somewhat confusing for the
user, and means that the user cannot easily set the cutoffs for a single
stringency.
Here we change the `set_cutoffs` method so it only sets the recommended
cutoffs for a single stringency, which has to be specified as an input
argument. The stringency is automatically set to be the default in case
it is the only stringency specified, and a `set_default_stringency`
method is added to the user can still change the default stringency at
any time after setting multiple …

`RecommendedCutoffMixin`: set only one stringency with `set_cutoffs`

---

aiida_pseudo/groups/mixins/cutoffs.py

Currently, pseudo families installed with `aiida-pseudo>=0.4.0` will
fail to work with the new API features in two ways, both related to the
addition of units for the recommended cutoffs:
* `delete_cutoffs` expects the units to be stored in the
`'_cutoffs_unit'` extras dictionary. Simply adding `None` as a default
to return in the `.pop()` call fixes this issue.
* `get_cutoffs_unit` will return a `KeyError` since the previously
configured stringencies did not include units. Here we can add an `if`
clause that check if the requested stringency _does_ have its cutoffs
set. Since the default unit was and is `eV`, we set this as the new unit
for the stringency. From then on the pseudo family will be "fixed".
Note: families installed with `aiida-pseudo<=0.3.0` will still cause
problems since …

`RecommendedCutoffMixin`: Add support for `aiida-pseudo>=0.4.0` families

---

.github/workflows/ci.yml

The CI uses `ubuntu-latest` as the image for the OS which recently got
updated to Ubuntu 20.04. This distribution no longer has `postgresql-10`
which was being installed. We replace this with `postgresql` which will
simply install whatever version of PostgreSQL is the default.

CI: use `postgresql` instead of `postgresql-10`

---

aiida_pseudo/groups/family/cutoffs.py
setup.json
tests/cli/test_family.py
tests/conftest.py
tests/groups/mixins/test_cutoffs.py

The `CutoffsFamily` was introduced in order to properly test the
`RecommendedCutoffsMixin`. It was even given an entry point but this was
just a requirement for the tests to work and it was never intended to
actually be used in production. However, there now seems an actual
usecase for this class as a substitute for the `SsspFamily` and
`PseudoDojoFamily` who also have the mixin and allow recommended cutoffs
to be defined but they come with strict rules and only official sets of
pseudopotentials are supported.
If one wants to create a custom pseudopotential family but still want to
use the recommended cutoff functionality, the `PseudoPotentialFamily`
base class doesn't suffice but the `CutoffsFamily` does. Now that we
actually consider the class to be used for production, a more aptly …

Rename `CutoffsFamily` to `CutoffsPseudoPotentialFamily`

---

aiida_pseudo/groups/mixins/cutoffs.py

Fixes #84 
Fixes #85 
Improve the error message in two cases:
* When deleting the final stringency with the `delete_cutoffs` method.
* An element requested with the `get_recommended_cutoffs` method does
not have a pseudo in the pseudo family.

`RecommendedCutoffMixin`: improve error messages

---

aiida_pseudo/cli/family.py
aiida_pseudo/cli/params/options.py
aiida_pseudo/cli/params/types.py
aiida_pseudo/groups/mixins/cutoffs.py
tests/cli/test_family.py
tests/groups/mixins/test_cutoffs.py

Fixes #96 
Although we now support specifying units for the recommended cutoffs,
the `family show` method had not been adapted for this feature.
Here we add the `-u/--unit` option to the `family show` method, making
sure to show the correct unit in the table header as well as adapting
the values in the columns by supplying the unit to the
`get_recommended_cutoffs` method.
There is also some refactoring regarding the validation of the
stringencies. The `RecommendedCutoffMixin.validate_stringency` method
was not being used, so we adapt the code for several methods with the
stringency input to rely on this validation method. This way we have a
consistent and succinct error message in case the user requests a
stringency that has not been configured.

CLI: Add support for units to `family show`

---

aiida_pseudo/data/pseudo/jthxml.py
aiida_pseudo/data/pseudo/pseudo.py
aiida_pseudo/data/pseudo/psf.py
aiida_pseudo/data/pseudo/psml.py
aiida_pseudo/data/pseudo/psp8.py
aiida_pseudo/data/pseudo/upf.py
aiida_pseudo/data/pseudo/vps.py
tests/data/pseudo/test_jthxml.py
tests/data/pseudo/test_pseudo.py
tests/data/pseudo/test_psf.py
tests/data/pseudo/test_psml.py
tests/data/pseudo/test_psp8.py
tests/data/pseudo/test_upf.py
tests/data/pseudo/test_vps.py

Fixes #87 
Currently, the source of the pseudopotential passed at construction time
of the `PseudoPotentialData` that represents it had to be a binary
stream. Here we introduce the possibility to allow the caller that pass
a `str` or `Path` object with the absolute path to the file content on
disk that should be wrapped.
There is a potential inefficiency in the implementation after this change.
It is not only the constructor of `SinglefileData`, and therefore our
plugin `PseudoPotentialData` and all its subclasses, that needs to be
able to support the different source types and convert the paths to a
stream if that is what passed, the `set_file` method, which is called by
the constructor needs to apply the same checks and conversions. Here, we
need to therefore make sure that the …

`PseudoPotentialData`: allow `str` or `Path` for `source` argument

---

setup.json

This reverts `383ab247c40ada60c22ce3673cbbc3efccd21f98`. The upper limit
is no longer necessary as the incompatibility of `sqlalchemy-utils` with
`sqlalchemy==1.4` has been solved downstream.

Dependencies: remove temporary upper limit for `sqlalchemy`

---

aiida_pseudo/cli/install.py
setup.json
tests/cli/test_install.py

Fixes #109 
The `cli.test_install:test_install_family_url` test was using a link to
the legacy version of the Materials Cloud Archive which has now been
taken offline, causing the test to fail. The link is updated to point to
the new server.

Replace SSSP link to legacy MC Archive

---

tests/cli/test_install.py
tests/cli/test_utils.py
tests/conftest.py

The `install family` command allows to install a family from an archive
that is directly provided via an HTTP URL. This was being tested
explicitly by using a URL from the Materials Cloud Archive. However,
this approach of actually retrieving from a URL has two main downsides:
* It will be potentially slow by having to download data from the web
* It is susceptible to random failures: if the URL is (temporarily) not
availabe, goes permanently goes offline, or the content changes.
That is why we  monkeypatch the ``PathOrUrl`` instead to simply return
the content of an archive that is created on the fly on the local disk.
The command expects that the parameter type returns an object that
contains the content of the archive under the ``content`` attribute.
To mimick this, we construct a …

Tests: do not rely on actual URL to test install family

---

aiida_pseudo/cli/install.py
aiida_pseudo/groups/family/pseudo_dojo.py
aiida_pseudo/groups/family/sssp.py

The `SsspConfiguration` and `PseudoDojoConfiguration` tuples were
defined using `collections.namedtuple`. These are replaced by using
`typing.NamedTuple` which not only provides type hints for the members
but it allows to define the `__str__` method, which makes it easier to
use the configuration in formatted strings.

Use `typing.NamedTuple` for pseudo family configurations

---

aiida_pseudo/data/pseudo/pseudo.py
aiida_pseudo/groups/family/pseudo.py
setup.cfg

To guarantee the reproducibility of local pre-commit as well as that of
the remote CI workflows, it is best to pin a version of `pylint`. Here
it is updated to the most recent version. This surfaces two new warnings
that are addressed.

Dependencies: update and pin `pylint==2.13.7`

---

.github/workflows/ci.yml
setup.cfg

The Python requirements are updated:
* Drop support for Python 3.6 and Python 3.7
* Add support for Python 3.10
To add support for Python 3.10, the minimum requirement for `pytest`
also had to be updated.

DevOps: Update Python version requirements

---

LICENSE.txt
pyproject.toml

The license file was named `LICENSE` but having `LICENSE.txt` with a
proper extension is better. The copyright year is also updated as well
as the reference to the license file in the `pyproject.toml`.

DevOps: Add proper file extension to license file

---

.github/workflows/ci.yml
aiida_pseudo/cli/__init__.py
aiida_pseudo/cli/install.py
aiida_pseudo/cli/list.py
aiida_pseudo/cli/params/arguments.py
aiida_pseudo/cli/root.py
aiida_pseudo/cli/utils.py
aiida_pseudo/data/pseudo/pseudo.py
aiida_pseudo/data/pseudo/upf.py
aiida_pseudo/data/pseudo/vps.py
aiida_pseudo/groups/family/pseudo.py
aiida_pseudo/groups/mixins/cutoffs.py
docs/source/conf.py
pyproject.toml
tests/cli/test_install.py
tests/cli/test_list.py
tests/cli/test_utils.py
tests/conftest.py
tests/data/pseudo/test_pseudo.py

Dependencies: update requirement `aiida-core~=2.0`
Adds compatibility with AiiDA v2.0. Notable changes:
* Entry points are now loaded through built-in modules instead of the
custom `reentry`, so `reentry scan` no longer needs to be called.
* Tab-completion now ships with `click` itself, so `click_completion`
and its manual activiation is removed.
* Update entry points from `aiida-core` by prefixing with `core.`
Also enable the `AIIDA_WARN_v3` environment variable in the `tests` job
of the CI workflow. This will print deprecation warnings from
`aiida-core`. These are also addressed in this commit:
* `Entity.objects` -> `Entity.collection`
* `Node.get_attribute` -> `Node.base.attributes.get`
* `Node.set_attribute` -> `Node.base.attributes.set`
* `Node.get_extra` -> `Node.base.extras.get`
* …

Dependencies: update requirement `aiida-core~=2.0`

---

pyproject.toml
tests/groups/family/test_pseudo.py

As of Python 3.10, the built-in module `distutils` has been deprecated
and will be removed in Python 3.12. It was being used to copy
directories and their content recursively. This has been replaced with
the `shutil.copytree` method.

Refactor: remove use of deprecated `distutils` module

---

tests/cli/test_install.py
tests/cli/test_utils.py
tests/conftest.py
tests/data/pseudo/test_pseudo.py
tests/groups/family/test_pseudo.py

The `tmpdir` fixture provided by `pytest` has been deprecated and is
replaced by the `tmp_path` fixture.
Note that the `tmpdir` used to return an instance of `LocalPath`, a
class defined by `pytest`, but `tmp_path` returns an instance of
`pathlib.Path` from the standard library.

Refactor: replace `tmpdir` fixture with `tmp_path`

---

.readthedocs.yml
docs/source/conf.py

The package is installed anyway for the build on ReadTheDocs so we can
simply import it instead of manually adding it to the Python path.

Docs: remove manual addition of package to `sys.path`

---

src/aiida_pseudo/data/pseudo/psml.py
tests/data/pseudo/test_psml.py
tests/fixtures/pseudos/psml/Ar.psml
tests/fixtures/pseudos/psml/He.psml
tests/fixtures/pseudos/psml/Ne.psml

`PsmlData`: Add parsing of Z-valence from file

---

src/aiida_pseudo/cli/family.py
tests/cli/test_family.py

Fixes #93 
Currently the `family cutoffs set` command requires that the JSON file that contains the cutoffs _only_ has the cutoff keys specified for each element. This is because the cutoffs are validated by the `RecommendedCutoffMixin.validate_cutoffs()` method, which doesn't allow for extraneous keys.
However, the  `.json`  file could have been adapted by the user from e.g. the SSSP `metadata.json` or some other dictionary that also contains other keys. As long as the cutoff keys are defined, we shouldn't raise an error just because there are other keys present.
Here we first filter the data loaded from the JSON file for the cutoffs, before passing the dictionary to the `set_cutoffs` method.

CLI: filter cutoffs from JSON file for family cutoffs set

---

docs/source/conf.py
docs/source/design.rst
src/aiida_pseudo/cli/family.py
src/aiida_pseudo/cli/install.py
src/aiida_pseudo/cli/params/types.py
tests/cli/test_family.py

One of the motivations of having dedicated and automated CLI commands to install established pseudpotential families like the SSSP or the Pseudo-dojo normconserving pseudopotentials is to try and prevent that the pseudopotentials or recommended cutoffs deviate from the official ones. However, the `family cutoffs set` command currently allows the user to change the recommended cutoffs easily through the CLI.
In order to prevent this, we block usage of the command for `SsspFamily` and `PseudoDojoFamily`'s, by adding an `exclude` input argument to the `PseudoPotentialFamilyParam`, where the entry points of the classes that should be disallowed can be provided. This is then used to adapt the option decorator for the `PSEUDO_POTENTIAL_FAMILY` input argument of `family cutoffs set`.
Note that …

CLI: block family cutoffs set for established families

---

pyproject.toml
src/aiida_pseudo/cli/params/options.py
src/aiida_pseudo/cli/root.py
tests/cli/test_root.py

Fixes #130 
Currently the CLI is broken with `aiida-core==2.1`. The reason is that we are using the `PROFILE` option, which relies on the command that it is attached to configure certain things, such as the context. In v2.1, the behavior was changed causing the commands to except because the `PROFILE` option cannot find certain attributes it expects in the context.
For the `PROFILE` option to work, the root command should use the class `aiida.cmdline.groups.VerdiCommandGroup` as its `cls`. This class defines a custom context class that is necessary. It also automatically provides the verbosity option for all subcommands, so the explicit declaration can now be removed.
The problem was not detected in the unit tests because they only show up when the root command is invoked. The unit tests …

CLI: update to be compatible with `aiida-core==2.1`

---

pyproject.toml
src/aiida_pseudo/cli/install.py
src/aiida_pseudo/cli/params/types.py

The following changes were necessary
* The `bad-continuation` was removed by `pylint`
* The `no-self-use` warning was moved to a plugin
* The `requests.get` methods need a timeout. It is set to 30 seconds for all calls. This should be largely sufficient. Note that the timeout is not a time limit on the entire response download; rather, an exception is raised if the server has not issued a response for timeout seconds, i.e., if no bytes have been received on the underlying socket for timeout seconds

DevOps: Update dependency `pylint==2.15.5`

---

src/aiida_pseudo/cli/family.py
src/aiida_pseudo/cli/install.py
src/aiida_pseudo/cli/params/types.py

Fixes #141 
Some of the commands imported a number of resources at the top of the modules that have large loading times on first import. This was causing the load time of the CLI to be ~1.5 seconds, even when just rendering the help message.
By moving the slow packages inside the commands themselves, the load time is reduced to a mere ~0.2 seconds. This makes the CLI much more snappy to use, especially when using tab-completion.

CLI: Reduce the load time significantly

---

src/aiida_pseudo/groups/mixins/cutoffs.py

Fixes #76 
A workaround was added in `v0.6` for families with recommended cutoffs that were installed with `v0.5` since that older version didn't explicitly store the units of the stringencies in the extras which the new API assumed would always be there.
The workaround would account for the lack of this extra and would automatically introduce it (in a sense migrating the old family to be compatible with the new API) the first time it would be requested.
Almost two years has passed since the release of `v0.6` which should have been plenty for existing families to have been migrated through this workaround and so it can now be removed.

`RecommendedCutoffMixin`: Remove workaround for stringency units

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/validate_release_tag.py
.pre-commit-config.yaml
.readthedocs.yml
docs/source/conf.py

The `setup-python` action is updated to `v4` which comes with built-in support for caching of the `pip` install step, so the `cache` action can be dropped.
The default version of Python for non-matrix based jobs is updated to 3.10 which allows to use the more robust `removeprefix` string method in the `validate_release_tag.py` file. This is more readable than the previous string slicing.

DevOps: Update Python version and `setup-python` action in CI/CD

---

README.md

The latest release `v1.0.0` was not included. It is compatible with the same Python and `aiida-core` versions as the `v0.x` series starting from `v0.8.0`.

DevOps: Update compatibility matrix in `README.md`

---

src/aiida_pseudo/cli/install.py
src/aiida_pseudo/groups/family/pseudo_dojo.py

Add the various configurations/urls for Pseudo-dojo v0.5, and add the option to the CLI install command.
Since the `.djrepo` files are missing the `hints` generated using the delta factor, fall back on the `ppgen_hints` provided by ONCVPSP in this case.

Add support for Pseudo-dojo v0.5

---

docs/source/howto.rst
docs/source/troubleshooting.rst
src/aiida_pseudo/cli/install.py
src/aiida_pseudo/cli/params/options.py
tests/cli/test_install.py
tests/groups/family/test_pseudo.py

Fixes #92 
Our workaround for installing an "established" family like a `SsspFamily` or `PseudoDojoFamily` required using the `install family` command, but this is explicitly forbidden since we do not want the user to be able to install an arbitrary set of pseudopotentials as one of these classes. This means there is currently no way to install the archive and metadata obtained with the `--download-only` option of the automated install commands as a proper `SsspFamily` or `PseudoDojoFamily`.
Here, we add the `--from-download` option to the automated install commands to allow the user to install the downloaded pseudopotentials and set the recommended cutoffs automatically for an `SsspFamily` or `PseudoDojoFamily`. The `--download-only` option now also produces a single `.aiida_pseudo` …

CLI: add install `--from-download` for sssp and pseudo-dojo

---

docs/source/howto.rst

Add more information on how the command will fail if the pseudopotential files do not respect the expected naming scheme and how the format can be specified explicitly as a fix.
I think with these instructions, the `aiida.orm.nodes.data.upf` module can be deprecated as in principle any family can be created.

Docs: Improve section on installing custom archive

---

docs/source/howto.rst

The provided snippet can be used to migrate an existing UPF family, created with the `aiida.orm.nodes.data.upf` module from `aiida-core`. A `PseudoPotentialFamily` will be created to which the existing `UpfData` nodes are added, after having been converted to the `UpfData` class of `aiida-pseudo`.

Docs: Add how to migrate from legacy UPF family

---

src/aiida_pseudo/cli/install.py
tests/cli/test_install.py

Fixes #165 
The `aiida-pseudo install sssp/pseudo-dojo` provide the `--download-only` option to only download the archive. This is useful in case a family needs to be installed on a machine without a (stable) internet connection. With this option, the archive can be downloaded on another machine first before transferring the file and installing it directly from the archive.
Currently, however, the install command always requires an AiiDA profile to be configured, even for the `--download-only` option in which case the command never needs access to the profile. Here, this requirement is removed by removing the `with_dbenv` decorator from the command. Instead, the profile is loaded manually inside the command at the point where it is really necessary.

CLI: Enable install `--download-only` without available profile

---

src/aiida_pseudo/data/pseudo/pseudo.py
tests/data/pseudo/test_pseudo.py

fixes #167 
For pseudo data, all we care about for the node is the hash of the file. So we could even think of overriding the _get_objects_to_hash and just return the md5 and element.

Hashing made with element and md5 checksum

---

docs/source/design.rst
docs/source/howto.rst

It is not directly obvious to users that AiiDA's group APIs can be used with pseudopotential families since they are simply groups themselves.

Docs: Explicitly state that AiiDA's `Group` API and CLI can be used

---

src/aiida_pseudo/data/pseudo/pseudo.py
tests/cli/test_install.py
tests/data/pseudo/test_pseudo.py

A recent release of `aiida-core` removed the import of `Config` directly from the module `aiida.manage.configuration` causing the tests to fail. It should now be imported from `aiida.manage.configuration.config.Config`.

Fix broken import of `aiida.manage.configuration.Config`

---

docs/source/design.rst

Hey All, 
I tried to use the documentation available regarding the design of a new pseudo-family and I found I need to make a few small-ish adjustments to make it work. I thought it would be nice to add them in the documentation. This pull request includes updates to the code snippets on the design section of the documentation, reflecting the adjustments I made. Looking forward to your feedback.

Udjusted the documentation regarding the creating of a pseudo family.

---

.github/workflows/cd.yml
.github/workflows/ci.yml
pyproject.toml
src/aiida_pseudo/data/pseudo/pseudo.py
tests/cli/test_family.py
tests/cli/test_install.py
tests/cli/test_list.py
tests/cli/test_utils.py
tests/conftest.py
tests/data/pseudo/test_jthxml.py
tests/data/pseudo/test_pseudo.py
tests/data/pseudo/test_psf.py
tests/data/pseudo/test_psml.py
tests/data/pseudo/test_psp8.py
tests/data/pseudo/test_upf.py
tests/data/pseudo/test_vps.py
tests/groups/family/test_pseudo.py
tests/groups/family/test_pseudo_dojo.py
tests/groups/family/test_sssp.py
tests/groups/mixins/test_cutoffs.py

Most notably, the `aiida_profile` and related fixtures now by default use a profile using the `core.sqlite_dos` storage plugin and define no broker. This means the PostgreSQL and RabbitMQ services are no longer required to run the tests.

Devops: Make use of the improved fixtures in `aiida-core`

---

src/aiida_pseudo/cli/install.py

Hey  All, 
I tried to download a version of pseudo dojo pseudopotentials however I couldn't due to : 
```
Report: downloading selected pseudopotentials archive...  [FAILED]
Critical: HTTPSConnectionPool(host='www.pseudo-dojo.org', port=443): Max retries exceeded with url: /pseudos/nc-fr-04_pbesol_standard_psp8.tgz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
```
As a quick fix we can bypass the certificate check when we download the specific pseudopotentials. Happy to hear any feedback. Thanks :D

Proposed fix for HTTPSConnection Issue with PseudoDojo

---

pyproject.toml

The release `sphinx-autoapi==3.4.0` causes the docs build to fail.
See https://github.com/readthedocs/sphinx-autoapi/issues/504

Devops: Pin requirement `sphinx-autoapi~=3.3.3`

---

.readthedocs.yml

Projects without an explicit configuration in `.readthedocs.yaml` are deprecated, see:
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

👌 Add path to sphinx `conf.py` to RTD configuration

---

pyproject.toml

The recent release v8.2 breaks the CLI from `aiida-core`. Until that is fixed, an upper limit is opposed as a temporary fix.

Dependencies: Add upper pin `click<8.2`

---

.github/workflows/cd.yml
.github/workflows/ci.yml
pyproject.toml

Hello,
a simple upgrade of a dependency does not crash aiida when importing it in python 3.13
https://github.com/hgrecco/pint/issues/2065

update pint dependency to python 3.13

---

tests/cli/test_install.py
tests/data/pseudo/test_pseudo.py

The `empty_config` context manager is used for some of the testing infrastructure of the installation commands. It relied on some methods for adapting the AiiDA configuration folder, whose API has been changed in
https://github.com/aiidateam/aiida-core/commit/9baf3ca96caa5577ec8ed6cef69512f430bb5675
Here we adapt the `empty_config` context manager to rely on the new API using the `AiiDAConfigDir`.

♻️ Fix tests
